services:
  astro-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astro-bun-app
    ports:
      - '4321:4321'
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - WEB_URL=${WEB_URL}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${HASH}.rule=Host(`${DOPX_HOST}`)'
      - 'traefik.http.routers.${HASH}.entrypoints=websecure'
      - 'traefik.http.routers.${HASH}.tls.certResolver=letsencrypt'
      - 'traefik.http.services.${HASH}.loadbalancer.server.port=${DOPX_PORT}'
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:4321/'
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./data:/app/data
networks:
  default:
    name: astro-network
    driver: bridge
